### ISSUE TITLE
Use StyledComponents for everything

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra.pw#37]
We started with JSS (material-UI's styling solution), then switched to styledcomponents, we should use styledcomponents for all future additions, and rewrite current stuff. Note that we still use the theme (for breakpoints, color, etc)

**Comment by Favna** [comment]
Not that I really mind either way but why not use MUI's JSS? 

Alternatively we could also use SCSS modules which allow variables and functions since it's SCSS. You can see how that works in one of our work's repos (that's open source): https://github.com/RWS-NL/air-node-packages/blob/master/packages/webcomponents/src/Button/Button.tsx

Basically you create a SCSS file and `import css from '/path/to/file.scss'` it then reference it as `css.classname` (for example if the class is `.button` then `css.button`).

(S)CSS modules are supported natively in create-react-app: https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/

**Comment by Favna** [comment]
![image](https://user-images.githubusercontent.com/4019718/72654263-198d0400-398f-11ea-9fb4-60fb03718161.png)
